development_task:
  description: >
    Develop the necessary code to have an mvp of a mobile app. To develop the code,
    have a look at the document containing the app's design, features and requirements.
    To find the document use the file_read_tool. Develop the code having in mind that it will
    be tested in an Expo-managed environment, therefore, the packages used in the project
    should be compatible with Expo and the project shouldn't have an ios or android
    folder or any code or configurations for a bare react native project.

    Once you finish generating the code, provide it to the qa_engineer.

  expected_output: >
    Code for a mobile app project in Expo. The code should be divided in a way that
    clearly indicates what piece of code should be in what file. For instance:
    <markdown>
    #App.js
    <code>...</code>
    </markdown>

  agent: mobile_developer

qa_task:
  description: >
    Analyze the code and perform one of the following steps depending on the results
    of the analysis.

    - If the code contains issues or bugs, generate a full report outlining the issues
    found on the code or any improvements you think could be implemented, so the mobile_developer
    can work on them. The report should contain a list of the bugs, issues or
    improvements and their respective solution.

    - If the code is good to go, pass it over to the document_specialist so he can
    turn it into a markdown-formatted document.

  expected_output: >
    Either a fully fledged report with the bugs or issues found on the code provided by the mobile_developer.
    Or a congrats message letting the mobile_developer know that the code is great and the project is
    ready to be tested on a mobile device.

  agent: qa_engineer

refactoring_task:
  description: >
    If the qa_engineer gives you a report back that means you need to work on some improvements
    to the code. If so:
    - Work on solving any issue or bug outlined on the report.
    Fix any necessary code to have an mvp of the mobile app. Remember that the code will
    be tested in an Expo-managed environment, therefore, the packages used in the project
    should be compatible with Expo and the project shouldn't have an ios or android
    folder or any code or configurations for a bare react native project.

    Give your refactored code to the document_specialist so he can paste it into
    a markdown document.

  expected_output: >
    Refactored and improved code for an Expo project. The code should be bug-free and ready
    to be tested.

  agent: mobile_developer

document_task:
  description: >
    Fill a markdown document with the code that will be provided to you.

    Make sure all the code is pasted with integrity in the markdown file.

    The file should be formatted in a way that clearly indicates what piece of code
    should be in what file. For instance:
    <markdown>
    #App.js
    <code>...</code>
    </markdown>
  expected_output: >
    A markdown file containing all the code for a mobile app project.
  agent: document_specialist