#!/usr/bin/env python
# from pydantic import BaseModel

# from crewai.flow import Flow, listen, start

# from mobile_app_shipping.crews.app_idea_crew.app_idea_crew import AppIdeaCrew

# from mobile_app_shipping.crews.app_design_crew.app_design_crew import AppDesignCrew

# from mobile_app_shipping.crews.app_development_crew.app_development_crew import AppDevelopmentCrew

# from flask import Flask, render_template, request

# import os

# import json

# import subprocess

# # =============== Flask App ===============
# app = Flask(__name__)
# concepts = []  # stores app ideas generated by Crew 1
# selected_concept = None
# flow_instance = None  # reference to running Flow


# class MobileAppFlow(Flow):

#     @start()
#     def kicking_off(self):
#         print("Generating Successful App idea")

#     @listen(kicking_off)
#     def kicking_off_idea_crew(self):
#         app_idea_crew = AppIdeaCrew()
#         result = app_idea_crew.crew().kickoff()

#     @listen(kicking_off_idea_crew)
#     def kicking_off_design_crew(self):
#         app_design_crew = AppDesignCrew()
#         app_design_crew.crew().kickoff()

#     @listen(kicking_off_design_crew)
#     def kicking_off_development_crew(self):
#         app_dev_crew = AppDevelopmentCrew()
#         app_dev_crew.crew().kickoff()

#     @listen(kicking_off_development_crew)
#     def wrapping_up(self):
#         print("Congratulations and take a look at the code!")


# def kickoff():
#     app_flow = MobileAppFlow()
#     app_flow.kickoff()


# def plot():
#     app_flow = MobileAppFlow()
#     app_flow.plot()


# if __name__ == "__main__":
#     kickoff()

#!/usr/bin/env python
import os
import time
import threading
import webbrowser
from flask import Flask, render_template, request
from pydantic import BaseModel
from crewai.flow import Flow, listen, start
from crewai.project import after_kickoff

# === Import your Crews ===
from mobile_app_shipping.crews.app_idea_crew.app_idea_crew import AppIdeaCrew
from mobile_app_shipping.crews.app_design_crew.app_design_crew import AppDesignCrew
from mobile_app_shipping.crews.app_development_crew.app_development_crew import AppDevelopmentCrew


# ======================================
# Flask setup for Human-in-the-Loop UI
# ======================================
app = Flask(__name__)
concepts = []          # stores Crew 1 outputs
selected_concept = ""  # stores user’s selected idea
flow_instance = None   # reference to current Flow instance


class MobileAppFlow(Flow):

    @start()
    def kicking_off(self):
        print("🚀 Generating Successful App Ideas...")

    @listen(kicking_off)
    def kicking_off_idea_crew(self):
        """Run Crew 1: App Idea Crew"""
        print("🎨 Running App Idea Crew...")
        app_idea_crew = AppIdeaCrew()
        result = app_idea_crew.crew().kickoff()

        global concepts
        if isinstance(result, dict) and "concepts" in result:
            concepts = result["concepts"]
        else:
            text = str(result)
            concepts = [line.strip("-• ").strip() for line in text.split("\n") if line.strip()][:3]

        print("✅ App ideas generated!")

    @after_kickoff
    def prep_web_interface(self):
        """Mark that the interface is ready but don't launch Flask here."""
        print("⚙️ Preparing to launch Human-in-the-Loop interface...")
        # just log readiness; we’ll start Flask in kickoff()
        return True

    def resume_after_selection(self, chosen_concept: str):
        """Called by Flask when the human selects a concept."""
        print(f"✅ Human selected: {chosen_concept}\n")

        print("🧠 Running App Design Crew...")
        design_crew = AppDesignCrew()
        design_result = design_crew.crew().kickoff(inputs={"selected_concept": chosen_concept})

        print("💻 Running App Development Crew...")
        dev_crew = AppDevelopmentCrew()
        dev_result = dev_crew.crew().kickoff()

        print("🎉 Workflow complete! Check the web interface for results.\n")
        return design_result, dev_result



# ======================================
# Flask Routes
# ======================================
@app.route("/")
def index():
    if not concepts:
        return "<h2>No app ideas generated yet. Run the flow first.</h2>"
    return render_template("select_concept.html", concepts=concepts)


@app.route("/select", methods=["POST"])
def select():
    global selected_concept
    choice_index = int(request.form["concept"])
    selected_concept = concepts[choice_index]

    design_result, dev_result = flow_instance.resume_after_selection(selected_concept)
    return render_template(
        "result.html",
        concept=selected_concept,
        design_result=design_result,
        dev_result=dev_result,
    )


# ======================================
# Entry Points
# ======================================
def kickoff():
    global flow_instance
    flow_instance = MobileAppFlow()
    flow_instance.kickoff()

    # ✅ Start Flask server after Crew 1 finishes, in a background thread
    def run_flask():
        port = int(os.environ.get("PORT", 5000))
        print(f"🌐 Starting Flask server on http://127.0.0.1:{port}")
        app.run(host="0.0.0.0", port=port, debug=False)

    flask_thread = threading.Thread(target=run_flask)
    flask_thread.daemon = True
    flask_thread.start()

    # ✅ Give Flask a moment to boot before opening browser
    time.sleep(2)

    # Automatically open browser if not production
    if os.environ.get("ENV") != "production":
        try:
            webbrowser.open("http://127.0.0.1:5000")
        except Exception as e:
            print(f"⚠️ Could not open browser automatically: {e}")

    print("✅ Flask server running — open http://127.0.0.1:5000 if it didn't open automatically.\n")

    # Keep main thread alive (since CrewAI flow ended)
    while True:
        time.sleep(5)



def plot():
    flow = MobileAppFlow()
    flow.plot()


if __name__ == "__main__":
    kickoff()