analysis_task:
  description: >
    Based on the following app idea '{selected_concept}',
    create a fully fledged report on the mobile app concept. Include the following sections:
    - Title
    - Introduction (Why you selected that app idea)
    - Features (What features the app will have)
    - Target Audience (Who is the app for)
    - Business Model (How the app will make money)
    - Marketing Strategy (How you will market the app)
    - Roadmap (What features will be added in the future)
    - Competitive Analysis (How the app will compare to the competition)
    - Technical Requirements (Flutter/Dart will be used; list key packages from pub.dev)
    - Conclusion (Summarize the app idea)
  expected_output: >
    A report both in JSON and markdown format.
  agent: business_analyst

design_task:
  description: >
    Make a written design of the user experience and user interface of the
    mobile app suggested by the business_analyst on the report. Make sure to include color
    palettes, style of the buttons, transitions, layout and all the details
    the mobile_developer needs to develop the app. To design the app consider
    the recommendations from the business_analyst such as target audience and
    features.

    Make sure the design includes what the following screens of the app will look like:
    - Home screen
    - Login screen
    - Profile screen
    - Settings screen
  expected_output: >
    A complete written design document of how the mobile app should look and work.
    On the document you should include the following sections:
    - Visuals (Colors, layout, elements, etc.)
    - Features (How the app should work; how to move from one screen to
    the other, how to log in, how to remove elements, etc.)

    Format the report as markdown without '```'
  agent: uxui_designer

image_mockup_task:
  description: >
    Use the 'stable_diffusion_gallery' tool to generate realistic mockups
    for each screen and save them under the 'static' folder.
    Be as concise as possible by following the design you suggest on the written design.

    Use a prompt describing the app’s design clearly, such as:
    “A modern mobile app interface for [concept name], featuring a sleek layout and intuitive design.”
  expected_output: >
    Several mockup images of the screens of the mobile app design.
  agent: uxui_designer