analysis_task:
  description: >
    Based on the following app idea '{selected_concept}',
    create a fully fledged report on the mobile app concept. Include the following sections:
    - Title
    - Introduction (Why you selected that app idea)
    - Features (What features the app will have)
    - Target Audience (Who is the app for)
    - Business Model (How the app will make money)
    - Marketing Strategy (How you will market the app)
    - Roadmap (What features will be added in the future)
    - Competitive Analysis (How the app will compare to the competition)
    - Technical Requirements (What technology will be used)
    - Conclusion (Summarize the app idea)

    Your final answer MUST be the report in valid HTML (with <html>, <head>, <body> tags)
    and must be saved into a file named "app_roadmap.html".
  expected_output: >
    A report both in JSON format for the uxui_designer and in HTML format for later presentation
    on the web.
  agent: business_analyst

design_task:
  description: >
    Make a written design of the user experience and user interface of the
    mobile app suggested by the business_analyst on the report. Make sure to include color
    palettes, style of the buttons, transitions, layout and all the details
    the mobile_developer needs to develop the app. To design the app consider
    the recommendations from the business_analyst such as target audience and
    features.
  expected_output: >
    A complete written design document of how the mobile app should look and work.
    On the document you should include the following sections:
    - Visuals (Colors, layout, elements, etc.)
    - Features (How the app should work; how to move from one screen to
    the other, how to log in, how to remove elements, etc.)

    Format the report as markdown without '```'
  agent: uxui_designer

image_mockup_task:
  description: >
    Use the 'stable_diffusion_generate' tool to generate a Dall-e image of a mockup
    of what the first screen of the mobile app would look like.
    Be as concise as possible by following the design you suggest on the written design.

    Use a prompt describing the app’s design clearly, such as:
    “A modern mobile app interface for [concept name], featuring a sleek layout and intuitive design.”

    Save the image as 'app_mockup.png'
  expected_output: >
    A png image of the mockup first screen of the mobile app.
  agent: uxui_designer